# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/lorenz/mineserver

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/lorenz/mineserver

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool..."
	/usr/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package
.PHONY : package/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool for source..."
	/usr/bin/cpack --config ./CPackSourceConfig.cmake /home/lorenz/mineserver/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source
.PHONY : package_source/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lorenz/mineserver/CMakeFiles /home/lorenz/mineserver/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lorenz/mineserver/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named mineserver

# Build rule for target.
mineserver: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mineserver
.PHONY : mineserver

# fast build rule for target.
mineserver/fast:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/build
.PHONY : mineserver/fast

#=============================================================================
# Target rules for targets named binlog

# Build rule for target.
binlog: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 binlog
.PHONY : binlog

# fast build rule for target.
binlog/fast:
	$(MAKE) -f plugins/CMakeFiles/binlog.dir/build.make plugins/CMakeFiles/binlog.dir/build
.PHONY : binlog/fast

#=============================================================================
# Target rules for targets named commands

# Build rule for target.
commands: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 commands
.PHONY : commands

# fast build rule for target.
commands/fast:
	$(MAKE) -f plugins/CMakeFiles/commands.dir/build.make plugins/CMakeFiles/commands.dir/build
.PHONY : commands/fast

#=============================================================================
# Target rules for targets named crapMobs

# Build rule for target.
crapMobs: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 crapMobs
.PHONY : crapMobs

# fast build rule for target.
crapMobs/fast:
	$(MAKE) -f plugins/CMakeFiles/crapMobs.dir/build.make plugins/CMakeFiles/crapMobs.dir/build
.PHONY : crapMobs/fast

#=============================================================================
# Target rules for targets named cursesui

# Build rule for target.
cursesui: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cursesui
.PHONY : cursesui

# fast build rule for target.
cursesui/fast:
	$(MAKE) -f plugins/CMakeFiles/cursesui.dir/build.make plugins/CMakeFiles/cursesui.dir/build
.PHONY : cursesui/fast

#=============================================================================
# Target rules for targets named filelog

# Build rule for target.
filelog: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 filelog
.PHONY : filelog

# fast build rule for target.
filelog/fast:
	$(MAKE) -f plugins/CMakeFiles/filelog.dir/build.make plugins/CMakeFiles/filelog.dir/build
.PHONY : filelog/fast

#=============================================================================
# Target rules for targets named flatpermissions

# Build rule for target.
flatpermissions: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 flatpermissions
.PHONY : flatpermissions

# fast build rule for target.
flatpermissions/fast:
	$(MAKE) -f plugins/CMakeFiles/flatpermissions.dir/build.make plugins/CMakeFiles/flatpermissions.dir/build
.PHONY : flatpermissions/fast

#=============================================================================
# Target rules for targets named nBreak

# Build rule for target.
nBreak: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 nBreak
.PHONY : nBreak

# fast build rule for target.
nBreak/fast:
	$(MAKE) -f plugins/CMakeFiles/nBreak.dir/build.make plugins/CMakeFiles/nBreak.dir/build
.PHONY : nBreak/fast

#=============================================================================
# Target rules for targets named nether

# Build rule for target.
nether: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 nether
.PHONY : nether

# fast build rule for target.
nether/fast:
	$(MAKE) -f plugins/CMakeFiles/nether.dir/build.make plugins/CMakeFiles/nether.dir/build
.PHONY : nether/fast

#=============================================================================
# Target rules for targets named passiveMobs

# Build rule for target.
passiveMobs: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 passiveMobs
.PHONY : passiveMobs

# fast build rule for target.
passiveMobs/fast:
	$(MAKE) -f plugins/CMakeFiles/passiveMobs.dir/build.make plugins/CMakeFiles/passiveMobs.dir/build
.PHONY : passiveMobs/fast

src/blocks/basic.o: src/blocks/basic.cpp.o
.PHONY : src/blocks/basic.o

# target to build an object file
src/blocks/basic.cpp.o:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/blocks/basic.cpp.o
.PHONY : src/blocks/basic.cpp.o

src/blocks/basic.i: src/blocks/basic.cpp.i
.PHONY : src/blocks/basic.i

# target to preprocess a source file
src/blocks/basic.cpp.i:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/blocks/basic.cpp.i
.PHONY : src/blocks/basic.cpp.i

src/blocks/basic.s: src/blocks/basic.cpp.s
.PHONY : src/blocks/basic.s

# target to generate assembly for a file
src/blocks/basic.cpp.s:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/blocks/basic.cpp.s
.PHONY : src/blocks/basic.cpp.s

src/blocks/bed.o: src/blocks/bed.cpp.o
.PHONY : src/blocks/bed.o

# target to build an object file
src/blocks/bed.cpp.o:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/blocks/bed.cpp.o
.PHONY : src/blocks/bed.cpp.o

src/blocks/bed.i: src/blocks/bed.cpp.i
.PHONY : src/blocks/bed.i

# target to preprocess a source file
src/blocks/bed.cpp.i:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/blocks/bed.cpp.i
.PHONY : src/blocks/bed.cpp.i

src/blocks/bed.s: src/blocks/bed.cpp.s
.PHONY : src/blocks/bed.s

# target to generate assembly for a file
src/blocks/bed.cpp.s:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/blocks/bed.cpp.s
.PHONY : src/blocks/bed.cpp.s

src/blocks/blockfurnace.o: src/blocks/blockfurnace.cpp.o
.PHONY : src/blocks/blockfurnace.o

# target to build an object file
src/blocks/blockfurnace.cpp.o:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/blocks/blockfurnace.cpp.o
.PHONY : src/blocks/blockfurnace.cpp.o

src/blocks/blockfurnace.i: src/blocks/blockfurnace.cpp.i
.PHONY : src/blocks/blockfurnace.i

# target to preprocess a source file
src/blocks/blockfurnace.cpp.i:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/blocks/blockfurnace.cpp.i
.PHONY : src/blocks/blockfurnace.cpp.i

src/blocks/blockfurnace.s: src/blocks/blockfurnace.cpp.s
.PHONY : src/blocks/blockfurnace.s

# target to generate assembly for a file
src/blocks/blockfurnace.cpp.s:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/blocks/blockfurnace.cpp.s
.PHONY : src/blocks/blockfurnace.cpp.s

src/blocks/cake.o: src/blocks/cake.cpp.o
.PHONY : src/blocks/cake.o

# target to build an object file
src/blocks/cake.cpp.o:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/blocks/cake.cpp.o
.PHONY : src/blocks/cake.cpp.o

src/blocks/cake.i: src/blocks/cake.cpp.i
.PHONY : src/blocks/cake.i

# target to preprocess a source file
src/blocks/cake.cpp.i:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/blocks/cake.cpp.i
.PHONY : src/blocks/cake.cpp.i

src/blocks/cake.s: src/blocks/cake.cpp.s
.PHONY : src/blocks/cake.s

# target to generate assembly for a file
src/blocks/cake.cpp.s:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/blocks/cake.cpp.s
.PHONY : src/blocks/cake.cpp.s

src/blocks/chest.o: src/blocks/chest.cpp.o
.PHONY : src/blocks/chest.o

# target to build an object file
src/blocks/chest.cpp.o:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/blocks/chest.cpp.o
.PHONY : src/blocks/chest.cpp.o

src/blocks/chest.i: src/blocks/chest.cpp.i
.PHONY : src/blocks/chest.i

# target to preprocess a source file
src/blocks/chest.cpp.i:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/blocks/chest.cpp.i
.PHONY : src/blocks/chest.cpp.i

src/blocks/chest.s: src/blocks/chest.cpp.s
.PHONY : src/blocks/chest.s

# target to generate assembly for a file
src/blocks/chest.cpp.s:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/blocks/chest.cpp.s
.PHONY : src/blocks/chest.cpp.s

src/blocks/default.o: src/blocks/default.cpp.o
.PHONY : src/blocks/default.o

# target to build an object file
src/blocks/default.cpp.o:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/blocks/default.cpp.o
.PHONY : src/blocks/default.cpp.o

src/blocks/default.i: src/blocks/default.cpp.i
.PHONY : src/blocks/default.i

# target to preprocess a source file
src/blocks/default.cpp.i:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/blocks/default.cpp.i
.PHONY : src/blocks/default.cpp.i

src/blocks/default.s: src/blocks/default.cpp.s
.PHONY : src/blocks/default.s

# target to generate assembly for a file
src/blocks/default.cpp.s:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/blocks/default.cpp.s
.PHONY : src/blocks/default.cpp.s

src/blocks/door.o: src/blocks/door.cpp.o
.PHONY : src/blocks/door.o

# target to build an object file
src/blocks/door.cpp.o:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/blocks/door.cpp.o
.PHONY : src/blocks/door.cpp.o

src/blocks/door.i: src/blocks/door.cpp.i
.PHONY : src/blocks/door.i

# target to preprocess a source file
src/blocks/door.cpp.i:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/blocks/door.cpp.i
.PHONY : src/blocks/door.cpp.i

src/blocks/door.s: src/blocks/door.cpp.s
.PHONY : src/blocks/door.s

# target to generate assembly for a file
src/blocks/door.cpp.s:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/blocks/door.cpp.s
.PHONY : src/blocks/door.cpp.s

src/blocks/falling.o: src/blocks/falling.cpp.o
.PHONY : src/blocks/falling.o

# target to build an object file
src/blocks/falling.cpp.o:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/blocks/falling.cpp.o
.PHONY : src/blocks/falling.cpp.o

src/blocks/falling.i: src/blocks/falling.cpp.i
.PHONY : src/blocks/falling.i

# target to preprocess a source file
src/blocks/falling.cpp.i:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/blocks/falling.cpp.i
.PHONY : src/blocks/falling.cpp.i

src/blocks/falling.s: src/blocks/falling.cpp.s
.PHONY : src/blocks/falling.s

# target to generate assembly for a file
src/blocks/falling.cpp.s:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/blocks/falling.cpp.s
.PHONY : src/blocks/falling.cpp.s

src/blocks/fire.o: src/blocks/fire.cpp.o
.PHONY : src/blocks/fire.o

# target to build an object file
src/blocks/fire.cpp.o:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/blocks/fire.cpp.o
.PHONY : src/blocks/fire.cpp.o

src/blocks/fire.i: src/blocks/fire.cpp.i
.PHONY : src/blocks/fire.i

# target to preprocess a source file
src/blocks/fire.cpp.i:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/blocks/fire.cpp.i
.PHONY : src/blocks/fire.cpp.i

src/blocks/fire.s: src/blocks/fire.cpp.s
.PHONY : src/blocks/fire.s

# target to generate assembly for a file
src/blocks/fire.cpp.s:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/blocks/fire.cpp.s
.PHONY : src/blocks/fire.cpp.s

src/blocks/ice.o: src/blocks/ice.cpp.o
.PHONY : src/blocks/ice.o

# target to build an object file
src/blocks/ice.cpp.o:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/blocks/ice.cpp.o
.PHONY : src/blocks/ice.cpp.o

src/blocks/ice.i: src/blocks/ice.cpp.i
.PHONY : src/blocks/ice.i

# target to preprocess a source file
src/blocks/ice.cpp.i:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/blocks/ice.cpp.i
.PHONY : src/blocks/ice.cpp.i

src/blocks/ice.s: src/blocks/ice.cpp.s
.PHONY : src/blocks/ice.s

# target to generate assembly for a file
src/blocks/ice.cpp.s:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/blocks/ice.cpp.s
.PHONY : src/blocks/ice.cpp.s

src/blocks/jackolantern.o: src/blocks/jackolantern.cpp.o
.PHONY : src/blocks/jackolantern.o

# target to build an object file
src/blocks/jackolantern.cpp.o:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/blocks/jackolantern.cpp.o
.PHONY : src/blocks/jackolantern.cpp.o

src/blocks/jackolantern.i: src/blocks/jackolantern.cpp.i
.PHONY : src/blocks/jackolantern.i

# target to preprocess a source file
src/blocks/jackolantern.cpp.i:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/blocks/jackolantern.cpp.i
.PHONY : src/blocks/jackolantern.cpp.i

src/blocks/jackolantern.s: src/blocks/jackolantern.cpp.s
.PHONY : src/blocks/jackolantern.s

# target to generate assembly for a file
src/blocks/jackolantern.cpp.s:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/blocks/jackolantern.cpp.s
.PHONY : src/blocks/jackolantern.cpp.s

src/blocks/ladder.o: src/blocks/ladder.cpp.o
.PHONY : src/blocks/ladder.o

# target to build an object file
src/blocks/ladder.cpp.o:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/blocks/ladder.cpp.o
.PHONY : src/blocks/ladder.cpp.o

src/blocks/ladder.i: src/blocks/ladder.cpp.i
.PHONY : src/blocks/ladder.i

# target to preprocess a source file
src/blocks/ladder.cpp.i:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/blocks/ladder.cpp.i
.PHONY : src/blocks/ladder.cpp.i

src/blocks/ladder.s: src/blocks/ladder.cpp.s
.PHONY : src/blocks/ladder.s

# target to generate assembly for a file
src/blocks/ladder.cpp.s:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/blocks/ladder.cpp.s
.PHONY : src/blocks/ladder.cpp.s

src/blocks/leaves.o: src/blocks/leaves.cpp.o
.PHONY : src/blocks/leaves.o

# target to build an object file
src/blocks/leaves.cpp.o:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/blocks/leaves.cpp.o
.PHONY : src/blocks/leaves.cpp.o

src/blocks/leaves.i: src/blocks/leaves.cpp.i
.PHONY : src/blocks/leaves.i

# target to preprocess a source file
src/blocks/leaves.cpp.i:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/blocks/leaves.cpp.i
.PHONY : src/blocks/leaves.cpp.i

src/blocks/leaves.s: src/blocks/leaves.cpp.s
.PHONY : src/blocks/leaves.s

# target to generate assembly for a file
src/blocks/leaves.cpp.s:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/blocks/leaves.cpp.s
.PHONY : src/blocks/leaves.cpp.s

src/blocks/liquid.o: src/blocks/liquid.cpp.o
.PHONY : src/blocks/liquid.o

# target to build an object file
src/blocks/liquid.cpp.o:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/blocks/liquid.cpp.o
.PHONY : src/blocks/liquid.cpp.o

src/blocks/liquid.i: src/blocks/liquid.cpp.i
.PHONY : src/blocks/liquid.i

# target to preprocess a source file
src/blocks/liquid.cpp.i:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/blocks/liquid.cpp.i
.PHONY : src/blocks/liquid.cpp.i

src/blocks/liquid.s: src/blocks/liquid.cpp.s
.PHONY : src/blocks/liquid.s

# target to generate assembly for a file
src/blocks/liquid.cpp.s:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/blocks/liquid.cpp.s
.PHONY : src/blocks/liquid.cpp.s

src/blocks/note.o: src/blocks/note.cpp.o
.PHONY : src/blocks/note.o

# target to build an object file
src/blocks/note.cpp.o:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/blocks/note.cpp.o
.PHONY : src/blocks/note.cpp.o

src/blocks/note.i: src/blocks/note.cpp.i
.PHONY : src/blocks/note.i

# target to preprocess a source file
src/blocks/note.cpp.i:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/blocks/note.cpp.i
.PHONY : src/blocks/note.cpp.i

src/blocks/note.s: src/blocks/note.cpp.s
.PHONY : src/blocks/note.s

# target to generate assembly for a file
src/blocks/note.cpp.s:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/blocks/note.cpp.s
.PHONY : src/blocks/note.cpp.s

src/blocks/plant.o: src/blocks/plant.cpp.o
.PHONY : src/blocks/plant.o

# target to build an object file
src/blocks/plant.cpp.o:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/blocks/plant.cpp.o
.PHONY : src/blocks/plant.cpp.o

src/blocks/plant.i: src/blocks/plant.cpp.i
.PHONY : src/blocks/plant.i

# target to preprocess a source file
src/blocks/plant.cpp.i:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/blocks/plant.cpp.i
.PHONY : src/blocks/plant.cpp.i

src/blocks/plant.s: src/blocks/plant.cpp.s
.PHONY : src/blocks/plant.s

# target to generate assembly for a file
src/blocks/plant.cpp.s:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/blocks/plant.cpp.s
.PHONY : src/blocks/plant.cpp.s

src/blocks/pumpkin.o: src/blocks/pumpkin.cpp.o
.PHONY : src/blocks/pumpkin.o

# target to build an object file
src/blocks/pumpkin.cpp.o:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/blocks/pumpkin.cpp.o
.PHONY : src/blocks/pumpkin.cpp.o

src/blocks/pumpkin.i: src/blocks/pumpkin.cpp.i
.PHONY : src/blocks/pumpkin.i

# target to preprocess a source file
src/blocks/pumpkin.cpp.i:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/blocks/pumpkin.cpp.i
.PHONY : src/blocks/pumpkin.cpp.i

src/blocks/pumpkin.s: src/blocks/pumpkin.cpp.s
.PHONY : src/blocks/pumpkin.s

# target to generate assembly for a file
src/blocks/pumpkin.cpp.s:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/blocks/pumpkin.cpp.s
.PHONY : src/blocks/pumpkin.cpp.s

src/blocks/redstone.o: src/blocks/redstone.cpp.o
.PHONY : src/blocks/redstone.o

# target to build an object file
src/blocks/redstone.cpp.o:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/blocks/redstone.cpp.o
.PHONY : src/blocks/redstone.cpp.o

src/blocks/redstone.i: src/blocks/redstone.cpp.i
.PHONY : src/blocks/redstone.i

# target to preprocess a source file
src/blocks/redstone.cpp.i:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/blocks/redstone.cpp.i
.PHONY : src/blocks/redstone.cpp.i

src/blocks/redstone.s: src/blocks/redstone.cpp.s
.PHONY : src/blocks/redstone.s

# target to generate assembly for a file
src/blocks/redstone.cpp.s:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/blocks/redstone.cpp.s
.PHONY : src/blocks/redstone.cpp.s

src/blocks/sign.o: src/blocks/sign.cpp.o
.PHONY : src/blocks/sign.o

# target to build an object file
src/blocks/sign.cpp.o:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/blocks/sign.cpp.o
.PHONY : src/blocks/sign.cpp.o

src/blocks/sign.i: src/blocks/sign.cpp.i
.PHONY : src/blocks/sign.i

# target to preprocess a source file
src/blocks/sign.cpp.i:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/blocks/sign.cpp.i
.PHONY : src/blocks/sign.cpp.i

src/blocks/sign.s: src/blocks/sign.cpp.s
.PHONY : src/blocks/sign.s

# target to generate assembly for a file
src/blocks/sign.cpp.s:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/blocks/sign.cpp.s
.PHONY : src/blocks/sign.cpp.s

src/blocks/snow.o: src/blocks/snow.cpp.o
.PHONY : src/blocks/snow.o

# target to build an object file
src/blocks/snow.cpp.o:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/blocks/snow.cpp.o
.PHONY : src/blocks/snow.cpp.o

src/blocks/snow.i: src/blocks/snow.cpp.i
.PHONY : src/blocks/snow.i

# target to preprocess a source file
src/blocks/snow.cpp.i:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/blocks/snow.cpp.i
.PHONY : src/blocks/snow.cpp.i

src/blocks/snow.s: src/blocks/snow.cpp.s
.PHONY : src/blocks/snow.s

# target to generate assembly for a file
src/blocks/snow.cpp.s:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/blocks/snow.cpp.s
.PHONY : src/blocks/snow.cpp.s

src/blocks/stair.o: src/blocks/stair.cpp.o
.PHONY : src/blocks/stair.o

# target to build an object file
src/blocks/stair.cpp.o:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/blocks/stair.cpp.o
.PHONY : src/blocks/stair.cpp.o

src/blocks/stair.i: src/blocks/stair.cpp.i
.PHONY : src/blocks/stair.i

# target to preprocess a source file
src/blocks/stair.cpp.i:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/blocks/stair.cpp.i
.PHONY : src/blocks/stair.cpp.i

src/blocks/stair.s: src/blocks/stair.cpp.s
.PHONY : src/blocks/stair.s

# target to generate assembly for a file
src/blocks/stair.cpp.s:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/blocks/stair.cpp.s
.PHONY : src/blocks/stair.cpp.s

src/blocks/step.o: src/blocks/step.cpp.o
.PHONY : src/blocks/step.o

# target to build an object file
src/blocks/step.cpp.o:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/blocks/step.cpp.o
.PHONY : src/blocks/step.cpp.o

src/blocks/step.i: src/blocks/step.cpp.i
.PHONY : src/blocks/step.i

# target to preprocess a source file
src/blocks/step.cpp.i:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/blocks/step.cpp.i
.PHONY : src/blocks/step.cpp.i

src/blocks/step.s: src/blocks/step.cpp.s
.PHONY : src/blocks/step.s

# target to generate assembly for a file
src/blocks/step.cpp.s:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/blocks/step.cpp.s
.PHONY : src/blocks/step.cpp.s

src/blocks/tnt.o: src/blocks/tnt.cpp.o
.PHONY : src/blocks/tnt.o

# target to build an object file
src/blocks/tnt.cpp.o:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/blocks/tnt.cpp.o
.PHONY : src/blocks/tnt.cpp.o

src/blocks/tnt.i: src/blocks/tnt.cpp.i
.PHONY : src/blocks/tnt.i

# target to preprocess a source file
src/blocks/tnt.cpp.i:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/blocks/tnt.cpp.i
.PHONY : src/blocks/tnt.cpp.i

src/blocks/tnt.s: src/blocks/tnt.cpp.s
.PHONY : src/blocks/tnt.s

# target to generate assembly for a file
src/blocks/tnt.cpp.s:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/blocks/tnt.cpp.s
.PHONY : src/blocks/tnt.cpp.s

src/blocks/torch.o: src/blocks/torch.cpp.o
.PHONY : src/blocks/torch.o

# target to build an object file
src/blocks/torch.cpp.o:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/blocks/torch.cpp.o
.PHONY : src/blocks/torch.cpp.o

src/blocks/torch.i: src/blocks/torch.cpp.i
.PHONY : src/blocks/torch.i

# target to preprocess a source file
src/blocks/torch.cpp.i:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/blocks/torch.cpp.i
.PHONY : src/blocks/torch.cpp.i

src/blocks/torch.s: src/blocks/torch.cpp.s
.PHONY : src/blocks/torch.s

# target to generate assembly for a file
src/blocks/torch.cpp.s:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/blocks/torch.cpp.s
.PHONY : src/blocks/torch.cpp.s

src/blocks/tracks.o: src/blocks/tracks.cpp.o
.PHONY : src/blocks/tracks.o

# target to build an object file
src/blocks/tracks.cpp.o:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/blocks/tracks.cpp.o
.PHONY : src/blocks/tracks.cpp.o

src/blocks/tracks.i: src/blocks/tracks.cpp.i
.PHONY : src/blocks/tracks.i

# target to preprocess a source file
src/blocks/tracks.cpp.i:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/blocks/tracks.cpp.i
.PHONY : src/blocks/tracks.cpp.i

src/blocks/tracks.s: src/blocks/tracks.cpp.s
.PHONY : src/blocks/tracks.s

# target to generate assembly for a file
src/blocks/tracks.cpp.s:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/blocks/tracks.cpp.s
.PHONY : src/blocks/tracks.cpp.s

src/blocks/wood.o: src/blocks/wood.cpp.o
.PHONY : src/blocks/wood.o

# target to build an object file
src/blocks/wood.cpp.o:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/blocks/wood.cpp.o
.PHONY : src/blocks/wood.cpp.o

src/blocks/wood.i: src/blocks/wood.cpp.i
.PHONY : src/blocks/wood.i

# target to preprocess a source file
src/blocks/wood.cpp.i:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/blocks/wood.cpp.i
.PHONY : src/blocks/wood.cpp.i

src/blocks/wood.s: src/blocks/wood.cpp.s
.PHONY : src/blocks/wood.s

# target to generate assembly for a file
src/blocks/wood.cpp.s:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/blocks/wood.cpp.s
.PHONY : src/blocks/wood.cpp.s

src/blocks/wool.o: src/blocks/wool.cpp.o
.PHONY : src/blocks/wool.o

# target to build an object file
src/blocks/wool.cpp.o:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/blocks/wool.cpp.o
.PHONY : src/blocks/wool.cpp.o

src/blocks/wool.i: src/blocks/wool.cpp.i
.PHONY : src/blocks/wool.i

# target to preprocess a source file
src/blocks/wool.cpp.i:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/blocks/wool.cpp.i
.PHONY : src/blocks/wool.cpp.i

src/blocks/wool.s: src/blocks/wool.cpp.s
.PHONY : src/blocks/wool.s

# target to generate assembly for a file
src/blocks/wool.cpp.s:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/blocks/wool.cpp.s
.PHONY : src/blocks/wool.cpp.s

src/blocks/workbench.o: src/blocks/workbench.cpp.o
.PHONY : src/blocks/workbench.o

# target to build an object file
src/blocks/workbench.cpp.o:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/blocks/workbench.cpp.o
.PHONY : src/blocks/workbench.cpp.o

src/blocks/workbench.i: src/blocks/workbench.cpp.i
.PHONY : src/blocks/workbench.i

# target to preprocess a source file
src/blocks/workbench.cpp.i:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/blocks/workbench.cpp.i
.PHONY : src/blocks/workbench.cpp.i

src/blocks/workbench.s: src/blocks/workbench.cpp.s
.PHONY : src/blocks/workbench.s

# target to generate assembly for a file
src/blocks/workbench.cpp.s:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/blocks/workbench.cpp.s
.PHONY : src/blocks/workbench.cpp.s

src/chat.o: src/chat.cpp.o
.PHONY : src/chat.o

# target to build an object file
src/chat.cpp.o:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/chat.cpp.o
.PHONY : src/chat.cpp.o

src/chat.i: src/chat.cpp.i
.PHONY : src/chat.i

# target to preprocess a source file
src/chat.cpp.i:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/chat.cpp.i
.PHONY : src/chat.cpp.i

src/chat.s: src/chat.cpp.s
.PHONY : src/chat.s

# target to generate assembly for a file
src/chat.cpp.s:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/chat.cpp.s
.PHONY : src/chat.cpp.s

src/cliScreen.o: src/cliScreen.cpp.o
.PHONY : src/cliScreen.o

# target to build an object file
src/cliScreen.cpp.o:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/cliScreen.cpp.o
.PHONY : src/cliScreen.cpp.o

src/cliScreen.i: src/cliScreen.cpp.i
.PHONY : src/cliScreen.i

# target to preprocess a source file
src/cliScreen.cpp.i:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/cliScreen.cpp.i
.PHONY : src/cliScreen.cpp.i

src/cliScreen.s: src/cliScreen.cpp.s
.PHONY : src/cliScreen.s

# target to generate assembly for a file
src/cliScreen.cpp.s:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/cliScreen.cpp.s
.PHONY : src/cliScreen.cpp.s

src/config/lexer.o: src/config/lexer.cpp.o
.PHONY : src/config/lexer.o

# target to build an object file
src/config/lexer.cpp.o:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/config/lexer.cpp.o
.PHONY : src/config/lexer.cpp.o

src/config/lexer.i: src/config/lexer.cpp.i
.PHONY : src/config/lexer.i

# target to preprocess a source file
src/config/lexer.cpp.i:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/config/lexer.cpp.i
.PHONY : src/config/lexer.cpp.i

src/config/lexer.s: src/config/lexer.cpp.s
.PHONY : src/config/lexer.s

# target to generate assembly for a file
src/config/lexer.cpp.s:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/config/lexer.cpp.s
.PHONY : src/config/lexer.cpp.s

src/config/node.o: src/config/node.cpp.o
.PHONY : src/config/node.o

# target to build an object file
src/config/node.cpp.o:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/config/node.cpp.o
.PHONY : src/config/node.cpp.o

src/config/node.i: src/config/node.cpp.i
.PHONY : src/config/node.i

# target to preprocess a source file
src/config/node.cpp.i:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/config/node.cpp.i
.PHONY : src/config/node.cpp.i

src/config/node.s: src/config/node.cpp.s
.PHONY : src/config/node.s

# target to generate assembly for a file
src/config/node.cpp.s:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/config/node.cpp.s
.PHONY : src/config/node.cpp.s

src/config/parser.o: src/config/parser.cpp.o
.PHONY : src/config/parser.o

# target to build an object file
src/config/parser.cpp.o:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/config/parser.cpp.o
.PHONY : src/config/parser.cpp.o

src/config/parser.i: src/config/parser.cpp.i
.PHONY : src/config/parser.i

# target to preprocess a source file
src/config/parser.cpp.i:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/config/parser.cpp.i
.PHONY : src/config/parser.cpp.i

src/config/parser.s: src/config/parser.cpp.s
.PHONY : src/config/parser.s

# target to generate assembly for a file
src/config/parser.cpp.s:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/config/parser.cpp.s
.PHONY : src/config/parser.cpp.s

src/config/scanner.o: src/config/scanner.cpp.o
.PHONY : src/config/scanner.o

# target to build an object file
src/config/scanner.cpp.o:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/config/scanner.cpp.o
.PHONY : src/config/scanner.cpp.o

src/config/scanner.i: src/config/scanner.cpp.i
.PHONY : src/config/scanner.i

# target to preprocess a source file
src/config/scanner.cpp.i:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/config/scanner.cpp.i
.PHONY : src/config/scanner.cpp.i

src/config/scanner.s: src/config/scanner.cpp.s
.PHONY : src/config/scanner.s

# target to generate assembly for a file
src/config/scanner.cpp.s:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/config/scanner.cpp.s
.PHONY : src/config/scanner.cpp.s

src/constants.o: src/constants.cpp.o
.PHONY : src/constants.o

# target to build an object file
src/constants.cpp.o:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/constants.cpp.o
.PHONY : src/constants.cpp.o

src/constants.i: src/constants.cpp.i
.PHONY : src/constants.i

# target to preprocess a source file
src/constants.cpp.i:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/constants.cpp.i
.PHONY : src/constants.cpp.i

src/constants.s: src/constants.cpp.s
.PHONY : src/constants.s

# target to generate assembly for a file
src/constants.cpp.s:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/constants.cpp.s
.PHONY : src/constants.cpp.s

src/furnace.o: src/furnace.cpp.o
.PHONY : src/furnace.o

# target to build an object file
src/furnace.cpp.o:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/furnace.cpp.o
.PHONY : src/furnace.cpp.o

src/furnace.i: src/furnace.cpp.i
.PHONY : src/furnace.i

# target to preprocess a source file
src/furnace.cpp.i:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/furnace.cpp.i
.PHONY : src/furnace.cpp.i

src/furnace.s: src/furnace.cpp.s
.PHONY : src/furnace.s

# target to generate assembly for a file
src/furnace.cpp.s:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/furnace.cpp.s
.PHONY : src/furnace.cpp.s

src/furnaceManager.o: src/furnaceManager.cpp.o
.PHONY : src/furnaceManager.o

# target to build an object file
src/furnaceManager.cpp.o:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/furnaceManager.cpp.o
.PHONY : src/furnaceManager.cpp.o

src/furnaceManager.i: src/furnaceManager.cpp.i
.PHONY : src/furnaceManager.i

# target to preprocess a source file
src/furnaceManager.cpp.i:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/furnaceManager.cpp.i
.PHONY : src/furnaceManager.cpp.i

src/furnaceManager.s: src/furnaceManager.cpp.s
.PHONY : src/furnaceManager.s

# target to generate assembly for a file
src/furnaceManager.cpp.s:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/furnaceManager.cpp.s
.PHONY : src/furnaceManager.cpp.s

src/inventory.o: src/inventory.cpp.o
.PHONY : src/inventory.o

# target to build an object file
src/inventory.cpp.o:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/inventory.cpp.o
.PHONY : src/inventory.cpp.o

src/inventory.i: src/inventory.cpp.i
.PHONY : src/inventory.i

# target to preprocess a source file
src/inventory.cpp.i:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/inventory.cpp.i
.PHONY : src/inventory.cpp.i

src/inventory.s: src/inventory.cpp.s
.PHONY : src/inventory.s

# target to generate assembly for a file
src/inventory.cpp.s:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/inventory.cpp.s
.PHONY : src/inventory.cpp.s

src/items/food.o: src/items/food.cpp.o
.PHONY : src/items/food.o

# target to build an object file
src/items/food.cpp.o:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/items/food.cpp.o
.PHONY : src/items/food.cpp.o

src/items/food.i: src/items/food.cpp.i
.PHONY : src/items/food.i

# target to preprocess a source file
src/items/food.cpp.i:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/items/food.cpp.i
.PHONY : src/items/food.cpp.i

src/items/food.s: src/items/food.cpp.s
.PHONY : src/items/food.s

# target to generate assembly for a file
src/items/food.cpp.s:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/items/food.cpp.s
.PHONY : src/items/food.cpp.s

src/items/itembasic.o: src/items/itembasic.cpp.o
.PHONY : src/items/itembasic.o

# target to build an object file
src/items/itembasic.cpp.o:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/items/itembasic.cpp.o
.PHONY : src/items/itembasic.cpp.o

src/items/itembasic.i: src/items/itembasic.cpp.i
.PHONY : src/items/itembasic.i

# target to preprocess a source file
src/items/itembasic.cpp.i:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/items/itembasic.cpp.i
.PHONY : src/items/itembasic.cpp.i

src/items/itembasic.s: src/items/itembasic.cpp.s
.PHONY : src/items/itembasic.s

# target to generate assembly for a file
src/items/itembasic.cpp.s:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/items/itembasic.cpp.s
.PHONY : src/items/itembasic.cpp.s

src/items/projectile.o: src/items/projectile.cpp.o
.PHONY : src/items/projectile.o

# target to build an object file
src/items/projectile.cpp.o:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/items/projectile.cpp.o
.PHONY : src/items/projectile.cpp.o

src/items/projectile.i: src/items/projectile.cpp.i
.PHONY : src/items/projectile.i

# target to preprocess a source file
src/items/projectile.cpp.i:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/items/projectile.cpp.i
.PHONY : src/items/projectile.cpp.i

src/items/projectile.s: src/items/projectile.cpp.s
.PHONY : src/items/projectile.s

# target to generate assembly for a file
src/items/projectile.cpp.s:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/items/projectile.cpp.s
.PHONY : src/items/projectile.cpp.s

src/lighting.o: src/lighting.cpp.o
.PHONY : src/lighting.o

# target to build an object file
src/lighting.cpp.o:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/lighting.cpp.o
.PHONY : src/lighting.cpp.o

src/lighting.i: src/lighting.cpp.i
.PHONY : src/lighting.i

# target to preprocess a source file
src/lighting.cpp.i:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/lighting.cpp.i
.PHONY : src/lighting.cpp.i

src/lighting.s: src/lighting.cpp.s
.PHONY : src/lighting.s

# target to generate assembly for a file
src/lighting.cpp.s:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/lighting.cpp.s
.PHONY : src/lighting.cpp.s

src/logger.o: src/logger.cpp.o
.PHONY : src/logger.o

# target to build an object file
src/logger.cpp.o:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/logger.cpp.o
.PHONY : src/logger.cpp.o

src/logger.i: src/logger.cpp.i
.PHONY : src/logger.i

# target to preprocess a source file
src/logger.cpp.i:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/logger.cpp.i
.PHONY : src/logger.cpp.i

src/logger.s: src/logger.cpp.s
.PHONY : src/logger.s

# target to generate assembly for a file
src/logger.cpp.s:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/logger.cpp.s
.PHONY : src/logger.cpp.s

src/map.o: src/map.cpp.o
.PHONY : src/map.o

# target to build an object file
src/map.cpp.o:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/map.cpp.o
.PHONY : src/map.cpp.o

src/map.i: src/map.cpp.i
.PHONY : src/map.i

# target to preprocess a source file
src/map.cpp.i:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/map.cpp.i
.PHONY : src/map.cpp.i

src/map.s: src/map.cpp.s
.PHONY : src/map.s

# target to generate assembly for a file
src/map.cpp.s:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/map.cpp.s
.PHONY : src/map.cpp.s

src/mcregion.o: src/mcregion.cpp.o
.PHONY : src/mcregion.o

# target to build an object file
src/mcregion.cpp.o:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/mcregion.cpp.o
.PHONY : src/mcregion.cpp.o

src/mcregion.i: src/mcregion.cpp.i
.PHONY : src/mcregion.i

# target to preprocess a source file
src/mcregion.cpp.i:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/mcregion.cpp.i
.PHONY : src/mcregion.cpp.i

src/mcregion.s: src/mcregion.cpp.s
.PHONY : src/mcregion.s

# target to generate assembly for a file
src/mcregion.cpp.s:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/mcregion.cpp.s
.PHONY : src/mcregion.cpp.s

src/metadata.o: src/metadata.cpp.o
.PHONY : src/metadata.o

# target to build an object file
src/metadata.cpp.o:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/metadata.cpp.o
.PHONY : src/metadata.cpp.o

src/metadata.i: src/metadata.cpp.i
.PHONY : src/metadata.i

# target to preprocess a source file
src/metadata.cpp.i:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/metadata.cpp.i
.PHONY : src/metadata.cpp.i

src/metadata.s: src/metadata.cpp.s
.PHONY : src/metadata.s

# target to generate assembly for a file
src/metadata.cpp.s:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/metadata.cpp.s
.PHONY : src/metadata.cpp.s

src/mineserver.o: src/mineserver.cpp.o
.PHONY : src/mineserver.o

# target to build an object file
src/mineserver.cpp.o:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/mineserver.cpp.o
.PHONY : src/mineserver.cpp.o

src/mineserver.i: src/mineserver.cpp.i
.PHONY : src/mineserver.i

# target to preprocess a source file
src/mineserver.cpp.i:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/mineserver.cpp.i
.PHONY : src/mineserver.cpp.i

src/mineserver.s: src/mineserver.cpp.s
.PHONY : src/mineserver.s

# target to generate assembly for a file
src/mineserver.cpp.s:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/mineserver.cpp.s
.PHONY : src/mineserver.cpp.s

src/mob.o: src/mob.cpp.o
.PHONY : src/mob.o

# target to build an object file
src/mob.cpp.o:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/mob.cpp.o
.PHONY : src/mob.cpp.o

src/mob.i: src/mob.cpp.i
.PHONY : src/mob.i

# target to preprocess a source file
src/mob.cpp.i:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/mob.cpp.i
.PHONY : src/mob.cpp.i

src/mob.s: src/mob.cpp.s
.PHONY : src/mob.s

# target to generate assembly for a file
src/mob.cpp.s:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/mob.cpp.s
.PHONY : src/mob.cpp.s

src/nbt.o: src/nbt.cpp.o
.PHONY : src/nbt.o

# target to build an object file
src/nbt.cpp.o:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/nbt.cpp.o
.PHONY : src/nbt.cpp.o

src/nbt.i: src/nbt.cpp.i
.PHONY : src/nbt.i

# target to preprocess a source file
src/nbt.cpp.i:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/nbt.cpp.i
.PHONY : src/nbt.cpp.i

src/nbt.s: src/nbt.cpp.s
.PHONY : src/nbt.s

# target to generate assembly for a file
src/nbt.cpp.s:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/nbt.cpp.s
.PHONY : src/nbt.cpp.s

src/packets.o: src/packets.cpp.o
.PHONY : src/packets.o

# target to build an object file
src/packets.cpp.o:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/packets.cpp.o
.PHONY : src/packets.cpp.o

src/packets.i: src/packets.cpp.i
.PHONY : src/packets.i

# target to preprocess a source file
src/packets.cpp.i:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/packets.cpp.i
.PHONY : src/packets.cpp.i

src/packets.s: src/packets.cpp.s
.PHONY : src/packets.s

# target to generate assembly for a file
src/packets.cpp.s:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/packets.cpp.s
.PHONY : src/packets.cpp.s

src/physics.o: src/physics.cpp.o
.PHONY : src/physics.o

# target to build an object file
src/physics.cpp.o:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/physics.cpp.o
.PHONY : src/physics.cpp.o

src/physics.i: src/physics.cpp.i
.PHONY : src/physics.i

# target to preprocess a source file
src/physics.cpp.i:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/physics.cpp.i
.PHONY : src/physics.cpp.i

src/physics.s: src/physics.cpp.s
.PHONY : src/physics.s

# target to generate assembly for a file
src/physics.cpp.s:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/physics.cpp.s
.PHONY : src/physics.cpp.s

src/plugin.o: src/plugin.cpp.o
.PHONY : src/plugin.o

# target to build an object file
src/plugin.cpp.o:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/plugin.cpp.o
.PHONY : src/plugin.cpp.o

src/plugin.i: src/plugin.cpp.i
.PHONY : src/plugin.i

# target to preprocess a source file
src/plugin.cpp.i:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/plugin.cpp.i
.PHONY : src/plugin.cpp.i

src/plugin.s: src/plugin.cpp.s
.PHONY : src/plugin.s

# target to generate assembly for a file
src/plugin.cpp.s:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/plugin.cpp.s
.PHONY : src/plugin.cpp.s

src/plugin_api.o: src/plugin_api.cpp.o
.PHONY : src/plugin_api.o

# target to build an object file
src/plugin_api.cpp.o:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/plugin_api.cpp.o
.PHONY : src/plugin_api.cpp.o

src/plugin_api.i: src/plugin_api.cpp.i
.PHONY : src/plugin_api.i

# target to preprocess a source file
src/plugin_api.cpp.i:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/plugin_api.cpp.i
.PHONY : src/plugin_api.cpp.i

src/plugin_api.s: src/plugin_api.cpp.s
.PHONY : src/plugin_api.s

# target to generate assembly for a file
src/plugin_api.cpp.s:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/plugin_api.cpp.s
.PHONY : src/plugin_api.cpp.s

src/random.o: src/random.cpp.o
.PHONY : src/random.o

# target to build an object file
src/random.cpp.o:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/random.cpp.o
.PHONY : src/random.cpp.o

src/random.i: src/random.cpp.i
.PHONY : src/random.i

# target to preprocess a source file
src/random.cpp.i:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/random.cpp.i
.PHONY : src/random.cpp.i

src/random.s: src/random.cpp.s
.PHONY : src/random.s

# target to generate assembly for a file
src/random.cpp.s:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/random.cpp.s
.PHONY : src/random.cpp.s

src/screenBase.o: src/screenBase.cpp.o
.PHONY : src/screenBase.o

# target to build an object file
src/screenBase.cpp.o:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/screenBase.cpp.o
.PHONY : src/screenBase.cpp.o

src/screenBase.i: src/screenBase.cpp.i
.PHONY : src/screenBase.i

# target to preprocess a source file
src/screenBase.cpp.i:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/screenBase.cpp.i
.PHONY : src/screenBase.cpp.i

src/screenBase.s: src/screenBase.cpp.s
.PHONY : src/screenBase.s

# target to generate assembly for a file
src/screenBase.cpp.s:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/screenBase.cpp.s
.PHONY : src/screenBase.cpp.s

src/sockets.o: src/sockets.cpp.o
.PHONY : src/sockets.o

# target to build an object file
src/sockets.cpp.o:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/sockets.cpp.o
.PHONY : src/sockets.cpp.o

src/sockets.i: src/sockets.cpp.i
.PHONY : src/sockets.i

# target to preprocess a source file
src/sockets.cpp.i:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/sockets.cpp.i
.PHONY : src/sockets.cpp.i

src/sockets.s: src/sockets.cpp.s
.PHONY : src/sockets.s

# target to generate assembly for a file
src/sockets.cpp.s:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/sockets.cpp.s
.PHONY : src/sockets.cpp.s

src/tools.o: src/tools.cpp.o
.PHONY : src/tools.o

# target to build an object file
src/tools.cpp.o:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/tools.cpp.o
.PHONY : src/tools.cpp.o

src/tools.i: src/tools.cpp.i
.PHONY : src/tools.i

# target to preprocess a source file
src/tools.cpp.i:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/tools.cpp.i
.PHONY : src/tools.cpp.i

src/tools.s: src/tools.cpp.s
.PHONY : src/tools.s

# target to generate assembly for a file
src/tools.cpp.s:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/tools.cpp.s
.PHONY : src/tools.cpp.s

src/tree.o: src/tree.cpp.o
.PHONY : src/tree.o

# target to build an object file
src/tree.cpp.o:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/tree.cpp.o
.PHONY : src/tree.cpp.o

src/tree.i: src/tree.cpp.i
.PHONY : src/tree.i

# target to preprocess a source file
src/tree.cpp.i:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/tree.cpp.i
.PHONY : src/tree.cpp.i

src/tree.s: src/tree.cpp.s
.PHONY : src/tree.s

# target to generate assembly for a file
src/tree.cpp.s:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/tree.cpp.s
.PHONY : src/tree.cpp.s

src/user.o: src/user.cpp.o
.PHONY : src/user.o

# target to build an object file
src/user.cpp.o:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/user.cpp.o
.PHONY : src/user.cpp.o

src/user.i: src/user.cpp.i
.PHONY : src/user.i

# target to preprocess a source file
src/user.cpp.i:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/user.cpp.i
.PHONY : src/user.cpp.i

src/user.s: src/user.cpp.s
.PHONY : src/user.s

# target to generate assembly for a file
src/user.cpp.s:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/user.cpp.s
.PHONY : src/user.cpp.s

src/worldgen/biomegen.o: src/worldgen/biomegen.cpp.o
.PHONY : src/worldgen/biomegen.o

# target to build an object file
src/worldgen/biomegen.cpp.o:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/worldgen/biomegen.cpp.o
.PHONY : src/worldgen/biomegen.cpp.o

src/worldgen/biomegen.i: src/worldgen/biomegen.cpp.i
.PHONY : src/worldgen/biomegen.i

# target to preprocess a source file
src/worldgen/biomegen.cpp.i:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/worldgen/biomegen.cpp.i
.PHONY : src/worldgen/biomegen.cpp.i

src/worldgen/biomegen.s: src/worldgen/biomegen.cpp.s
.PHONY : src/worldgen/biomegen.s

# target to generate assembly for a file
src/worldgen/biomegen.cpp.s:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/worldgen/biomegen.cpp.s
.PHONY : src/worldgen/biomegen.cpp.s

src/worldgen/cavegen.o: src/worldgen/cavegen.cpp.o
.PHONY : src/worldgen/cavegen.o

# target to build an object file
src/worldgen/cavegen.cpp.o:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/worldgen/cavegen.cpp.o
.PHONY : src/worldgen/cavegen.cpp.o

src/worldgen/cavegen.i: src/worldgen/cavegen.cpp.i
.PHONY : src/worldgen/cavegen.i

# target to preprocess a source file
src/worldgen/cavegen.cpp.i:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/worldgen/cavegen.cpp.i
.PHONY : src/worldgen/cavegen.cpp.i

src/worldgen/cavegen.s: src/worldgen/cavegen.cpp.s
.PHONY : src/worldgen/cavegen.s

# target to generate assembly for a file
src/worldgen/cavegen.cpp.s:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/worldgen/cavegen.cpp.s
.PHONY : src/worldgen/cavegen.cpp.s

src/worldgen/eximgen.o: src/worldgen/eximgen.cpp.o
.PHONY : src/worldgen/eximgen.o

# target to build an object file
src/worldgen/eximgen.cpp.o:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/worldgen/eximgen.cpp.o
.PHONY : src/worldgen/eximgen.cpp.o

src/worldgen/eximgen.i: src/worldgen/eximgen.cpp.i
.PHONY : src/worldgen/eximgen.i

# target to preprocess a source file
src/worldgen/eximgen.cpp.i:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/worldgen/eximgen.cpp.i
.PHONY : src/worldgen/eximgen.cpp.i

src/worldgen/eximgen.s: src/worldgen/eximgen.cpp.s
.PHONY : src/worldgen/eximgen.s

# target to generate assembly for a file
src/worldgen/eximgen.cpp.s:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/worldgen/eximgen.cpp.s
.PHONY : src/worldgen/eximgen.cpp.s

src/worldgen/heavengen.o: src/worldgen/heavengen.cpp.o
.PHONY : src/worldgen/heavengen.o

# target to build an object file
src/worldgen/heavengen.cpp.o:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/worldgen/heavengen.cpp.o
.PHONY : src/worldgen/heavengen.cpp.o

src/worldgen/heavengen.i: src/worldgen/heavengen.cpp.i
.PHONY : src/worldgen/heavengen.i

# target to preprocess a source file
src/worldgen/heavengen.cpp.i:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/worldgen/heavengen.cpp.i
.PHONY : src/worldgen/heavengen.cpp.i

src/worldgen/heavengen.s: src/worldgen/heavengen.cpp.s
.PHONY : src/worldgen/heavengen.s

# target to generate assembly for a file
src/worldgen/heavengen.cpp.s:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/worldgen/heavengen.cpp.s
.PHONY : src/worldgen/heavengen.cpp.s

src/worldgen/mapgen.o: src/worldgen/mapgen.cpp.o
.PHONY : src/worldgen/mapgen.o

# target to build an object file
src/worldgen/mapgen.cpp.o:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/worldgen/mapgen.cpp.o
.PHONY : src/worldgen/mapgen.cpp.o

src/worldgen/mapgen.i: src/worldgen/mapgen.cpp.i
.PHONY : src/worldgen/mapgen.i

# target to preprocess a source file
src/worldgen/mapgen.cpp.i:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/worldgen/mapgen.cpp.i
.PHONY : src/worldgen/mapgen.cpp.i

src/worldgen/mapgen.s: src/worldgen/mapgen.cpp.s
.PHONY : src/worldgen/mapgen.s

# target to generate assembly for a file
src/worldgen/mapgen.cpp.s:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/worldgen/mapgen.cpp.s
.PHONY : src/worldgen/mapgen.cpp.s

src/worldgen/nethergen.o: src/worldgen/nethergen.cpp.o
.PHONY : src/worldgen/nethergen.o

# target to build an object file
src/worldgen/nethergen.cpp.o:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/worldgen/nethergen.cpp.o
.PHONY : src/worldgen/nethergen.cpp.o

src/worldgen/nethergen.i: src/worldgen/nethergen.cpp.i
.PHONY : src/worldgen/nethergen.i

# target to preprocess a source file
src/worldgen/nethergen.cpp.i:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/worldgen/nethergen.cpp.i
.PHONY : src/worldgen/nethergen.cpp.i

src/worldgen/nethergen.s: src/worldgen/nethergen.cpp.s
.PHONY : src/worldgen/nethergen.s

# target to generate assembly for a file
src/worldgen/nethergen.cpp.s:
	$(MAKE) -f CMakeFiles/mineserver.dir/build.make CMakeFiles/mineserver.dir/src/worldgen/nethergen.cpp.s
.PHONY : src/worldgen/nethergen.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... mineserver"
	@echo "... package"
	@echo "... package_source"
	@echo "... rebuild_cache"
	@echo "... binlog"
	@echo "... commands"
	@echo "... crapMobs"
	@echo "... cursesui"
	@echo "... filelog"
	@echo "... flatpermissions"
	@echo "... nBreak"
	@echo "... nether"
	@echo "... passiveMobs"
	@echo "... src/blocks/basic.o"
	@echo "... src/blocks/basic.i"
	@echo "... src/blocks/basic.s"
	@echo "... src/blocks/bed.o"
	@echo "... src/blocks/bed.i"
	@echo "... src/blocks/bed.s"
	@echo "... src/blocks/blockfurnace.o"
	@echo "... src/blocks/blockfurnace.i"
	@echo "... src/blocks/blockfurnace.s"
	@echo "... src/blocks/cake.o"
	@echo "... src/blocks/cake.i"
	@echo "... src/blocks/cake.s"
	@echo "... src/blocks/chest.o"
	@echo "... src/blocks/chest.i"
	@echo "... src/blocks/chest.s"
	@echo "... src/blocks/default.o"
	@echo "... src/blocks/default.i"
	@echo "... src/blocks/default.s"
	@echo "... src/blocks/door.o"
	@echo "... src/blocks/door.i"
	@echo "... src/blocks/door.s"
	@echo "... src/blocks/falling.o"
	@echo "... src/blocks/falling.i"
	@echo "... src/blocks/falling.s"
	@echo "... src/blocks/fire.o"
	@echo "... src/blocks/fire.i"
	@echo "... src/blocks/fire.s"
	@echo "... src/blocks/ice.o"
	@echo "... src/blocks/ice.i"
	@echo "... src/blocks/ice.s"
	@echo "... src/blocks/jackolantern.o"
	@echo "... src/blocks/jackolantern.i"
	@echo "... src/blocks/jackolantern.s"
	@echo "... src/blocks/ladder.o"
	@echo "... src/blocks/ladder.i"
	@echo "... src/blocks/ladder.s"
	@echo "... src/blocks/leaves.o"
	@echo "... src/blocks/leaves.i"
	@echo "... src/blocks/leaves.s"
	@echo "... src/blocks/liquid.o"
	@echo "... src/blocks/liquid.i"
	@echo "... src/blocks/liquid.s"
	@echo "... src/blocks/note.o"
	@echo "... src/blocks/note.i"
	@echo "... src/blocks/note.s"
	@echo "... src/blocks/plant.o"
	@echo "... src/blocks/plant.i"
	@echo "... src/blocks/plant.s"
	@echo "... src/blocks/pumpkin.o"
	@echo "... src/blocks/pumpkin.i"
	@echo "... src/blocks/pumpkin.s"
	@echo "... src/blocks/redstone.o"
	@echo "... src/blocks/redstone.i"
	@echo "... src/blocks/redstone.s"
	@echo "... src/blocks/sign.o"
	@echo "... src/blocks/sign.i"
	@echo "... src/blocks/sign.s"
	@echo "... src/blocks/snow.o"
	@echo "... src/blocks/snow.i"
	@echo "... src/blocks/snow.s"
	@echo "... src/blocks/stair.o"
	@echo "... src/blocks/stair.i"
	@echo "... src/blocks/stair.s"
	@echo "... src/blocks/step.o"
	@echo "... src/blocks/step.i"
	@echo "... src/blocks/step.s"
	@echo "... src/blocks/tnt.o"
	@echo "... src/blocks/tnt.i"
	@echo "... src/blocks/tnt.s"
	@echo "... src/blocks/torch.o"
	@echo "... src/blocks/torch.i"
	@echo "... src/blocks/torch.s"
	@echo "... src/blocks/tracks.o"
	@echo "... src/blocks/tracks.i"
	@echo "... src/blocks/tracks.s"
	@echo "... src/blocks/wood.o"
	@echo "... src/blocks/wood.i"
	@echo "... src/blocks/wood.s"
	@echo "... src/blocks/wool.o"
	@echo "... src/blocks/wool.i"
	@echo "... src/blocks/wool.s"
	@echo "... src/blocks/workbench.o"
	@echo "... src/blocks/workbench.i"
	@echo "... src/blocks/workbench.s"
	@echo "... src/chat.o"
	@echo "... src/chat.i"
	@echo "... src/chat.s"
	@echo "... src/cliScreen.o"
	@echo "... src/cliScreen.i"
	@echo "... src/cliScreen.s"
	@echo "... src/config/lexer.o"
	@echo "... src/config/lexer.i"
	@echo "... src/config/lexer.s"
	@echo "... src/config/node.o"
	@echo "... src/config/node.i"
	@echo "... src/config/node.s"
	@echo "... src/config/parser.o"
	@echo "... src/config/parser.i"
	@echo "... src/config/parser.s"
	@echo "... src/config/scanner.o"
	@echo "... src/config/scanner.i"
	@echo "... src/config/scanner.s"
	@echo "... src/constants.o"
	@echo "... src/constants.i"
	@echo "... src/constants.s"
	@echo "... src/furnace.o"
	@echo "... src/furnace.i"
	@echo "... src/furnace.s"
	@echo "... src/furnaceManager.o"
	@echo "... src/furnaceManager.i"
	@echo "... src/furnaceManager.s"
	@echo "... src/inventory.o"
	@echo "... src/inventory.i"
	@echo "... src/inventory.s"
	@echo "... src/items/food.o"
	@echo "... src/items/food.i"
	@echo "... src/items/food.s"
	@echo "... src/items/itembasic.o"
	@echo "... src/items/itembasic.i"
	@echo "... src/items/itembasic.s"
	@echo "... src/items/projectile.o"
	@echo "... src/items/projectile.i"
	@echo "... src/items/projectile.s"
	@echo "... src/lighting.o"
	@echo "... src/lighting.i"
	@echo "... src/lighting.s"
	@echo "... src/logger.o"
	@echo "... src/logger.i"
	@echo "... src/logger.s"
	@echo "... src/map.o"
	@echo "... src/map.i"
	@echo "... src/map.s"
	@echo "... src/mcregion.o"
	@echo "... src/mcregion.i"
	@echo "... src/mcregion.s"
	@echo "... src/metadata.o"
	@echo "... src/metadata.i"
	@echo "... src/metadata.s"
	@echo "... src/mineserver.o"
	@echo "... src/mineserver.i"
	@echo "... src/mineserver.s"
	@echo "... src/mob.o"
	@echo "... src/mob.i"
	@echo "... src/mob.s"
	@echo "... src/nbt.o"
	@echo "... src/nbt.i"
	@echo "... src/nbt.s"
	@echo "... src/packets.o"
	@echo "... src/packets.i"
	@echo "... src/packets.s"
	@echo "... src/physics.o"
	@echo "... src/physics.i"
	@echo "... src/physics.s"
	@echo "... src/plugin.o"
	@echo "... src/plugin.i"
	@echo "... src/plugin.s"
	@echo "... src/plugin_api.o"
	@echo "... src/plugin_api.i"
	@echo "... src/plugin_api.s"
	@echo "... src/random.o"
	@echo "... src/random.i"
	@echo "... src/random.s"
	@echo "... src/screenBase.o"
	@echo "... src/screenBase.i"
	@echo "... src/screenBase.s"
	@echo "... src/sockets.o"
	@echo "... src/sockets.i"
	@echo "... src/sockets.s"
	@echo "... src/tools.o"
	@echo "... src/tools.i"
	@echo "... src/tools.s"
	@echo "... src/tree.o"
	@echo "... src/tree.i"
	@echo "... src/tree.s"
	@echo "... src/user.o"
	@echo "... src/user.i"
	@echo "... src/user.s"
	@echo "... src/worldgen/biomegen.o"
	@echo "... src/worldgen/biomegen.i"
	@echo "... src/worldgen/biomegen.s"
	@echo "... src/worldgen/cavegen.o"
	@echo "... src/worldgen/cavegen.i"
	@echo "... src/worldgen/cavegen.s"
	@echo "... src/worldgen/eximgen.o"
	@echo "... src/worldgen/eximgen.i"
	@echo "... src/worldgen/eximgen.s"
	@echo "... src/worldgen/heavengen.o"
	@echo "... src/worldgen/heavengen.i"
	@echo "... src/worldgen/heavengen.s"
	@echo "... src/worldgen/mapgen.o"
	@echo "... src/worldgen/mapgen.i"
	@echo "... src/worldgen/mapgen.s"
	@echo "... src/worldgen/nethergen.o"
	@echo "... src/worldgen/nethergen.i"
	@echo "... src/worldgen/nethergen.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

